source "https://rubygems.org"

# --- Default Gems ---
gem "rails", "~> 7.2.2"
gem "sprockets-rails"
gem "sqlite3", ">= 1.4"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

# --- UI Gems (Bootstrap 5) ---
gem "bootstrap", "~> 5.3"
gem "sassc-rails"

# --- Additional Gems ---
gem "devise"           # Auth
gem "cancancan"        # Permissions
gem "money-rails"      # Safe Math

# -- Testing Gems ---
group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false

  gem "rubocop-rails", require: false
  gem "annotate"
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
